arangodb:
  database: wpdbase
  user: root
  password: root
  host: localhost
  port: 8529
server:
  port: 8443
  ssl:
    enabled: true
    key-store: src\main\resources\bootsecurity.p12
    key-store-password: bootsecurity
    key-store-type: PKCS12
    key-alias: bootsecurity
